from django.conf.urls import patterns, url
from noddymix.apps.audio import views

urlpatterns = patterns('',
                       url(r'^$', views.new_releases, name="homepage"),
                       url(r'^heavy/$', views.heavy_rotation,
                           name="heavy_rotation"),
                       url(r"^top/$", views.top_playlists, 
                           name="top_playlists"),
                       
                       url(r'^favorites/$', views.favorites, name="favorites"),
                       url(r'^playlists/$', views.playlists, name="playlists"),
                       url(r'^history/$', views.history, name="history"),
                       url(r'^queue/$', views.queue, name="queue"),
                                              
                       url(r'^s/(?P<id>\d+)/$', views.song, name="song"),
                       url(r'^s/(?P<id>\d+)/play/$', views.song_play, 
                           name="song_play"),
                                              
                       url(r"^p/(?P<id>\d+)/$", views.playlist,
                           name="playlist"),
                       url(r"^p/(?P<id>\d+)/details/json/$", 
                           views.playlist_details_json,
                           name="playlist_details_json"),
                       url(r"^p/t/(?P<id>\d+)/$", views.playlist_temp,
                           name="playlist_temp"),
                       url(r"^p/new/$", views.playlist_new, 
                           name="playlist_new"),
                       url(r"^p/t/new/$", views.playlist_temp_new, 
                           name="playlist_temp_new"),
                       
                       url(r"^p/(?P<id>\d+)/order/songs/$", 
                           views.playlist_order_songs,
                           name="playlist_order_songs"),
                       url(r"^p/t/(?P<id>\d+)/order/songs/$", 
                           views.playlist_temp_order_songs,
                           name="playlist_temp_order_songs"),
                       url(r"^p/(?P<id>\d+)/add/songs/$", 
                           views.playlist_add_songs,
                           name="playlist_add_songs"),
                        url(r"^p/t/(?P<id>\d+)/add/songs/$", 
                           views.playlist_temp_add_songs,
                           name="playlist_temp_add_songs"),
                       url(r"^p/(?P<id>\d+)/delete/songs/$", 
                           views.playlist_delete_songs,
                           name="playlist_delete_songs"),
                       url(r"^p/t/(?P<id>\d+)/delete/songs/$", 
                           views.playlist_temp_delete_songs,
                           name="playlist_temp_delete_songs"),
                       
                       url(r"^p/(?P<id>\d+)/rename/$", views.playlist_rename, 
                           name="playlist_rename"),
                       url(r"^p/t/(?P<id>\d+)/rename/$", 
                           views.playlist_temp_rename, 
                           name="playlist_temp_rename"),
                       url(r"^p/(?P<id>\d+)/delete/$", views.playlist_delete, 
                           name="playlist_delete"),
                       url(r"^p/t/(?P<id>\d+)/delete/$", 
                           views.playlist_temp_delete,
                           name="playlist_temp_delete"),
                       url(r"^p/(?P<id>\d+)/lock/$", views.playlist_lock, 
                           name="playlist_lock"),
                       url(r"^p/(?P<id>\d+)/unlock/$", views.playlist_unlock,
                           name="playlist_delete"),
                       
                       url(r"^p/(?P<id>\d+)/subscribers/$", 
                           views.playlist_subscribers, 
                           name="playlist_subscribers"),
                       url(r"^p/(?P<id>\d+)/subscribe/$", 
                           views.playlist_subscribe, 
                           name="playlist_subscribe"),
                       url(r"^p/(?P<id>\d+)/unsubscribe/$", 
                           views.playlist_unsubscribe, 
                           name="playlist_unsubscribe"),
                       )

